import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css"; // Make sure globals.css is correctly imported

// Initialize the Geist font and Geist_Mono font with variables
const geistSans = Geist({
  variable: "--font-geist-sans", // Define the CSS variable for Geist font
  subsets: ["latin"], // Include specific subsets
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Define the CSS variable for Geist Mono font
  subsets: ["latin"], // Include specific subsets
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// Metadata for the app (title, description)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
